Vagrant.configure("2") do |config|
  config.vm.define :clienteUbuntu do |clienteUbuntu|
  clienteUbuntu.vm.box = "bento/ubuntu-20.04"
  clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
  clienteUbuntu.vm.hostname = "clienteUbuntu"
  end
  config.vm.define :servidorUbuntu do |servidorUbuntu|
  servidorUbuntu.vm.box = "bento/ubuntu-20.04"
  servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
  servidorUbuntu.vm.hostname = "servidorUbuntu"
  servidorUbuntu.vm.synced_folder "./sync", "/home/vagrant"
  servidorUbuntu.vm.provision :shell, path: "bootstrapServidor.sh" 
  end
  config.vm.define :tensorFlow do |tensorFlow|
  tensorFlow.vm.box = "gt50/tensorflow"
  tensorFlow.vm.network :private_network, ip: "192.168.100.4"
  tensorFlow.vm.hostname = "tensorFlow"
  end
end