# -*- mode: ruby -*-
# vi: set ft=ruby :


$install_puppet = <<-PUPPET
sudo apt-get update -y
sudo apt-get install -y puppet
PUPPET


Vagrant.configure("2") do |config|
  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-20.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
  end
  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.provision "shell", path: "script.sh"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end

  config.vm.define :puppetServer do |puppetServer|
    puppetServer.vm.box = "bento/ubuntu-20.04"
    puppetServer.vm.hostname = "puppetServer"
    puppetServer.vm.network :private_network, ip: "192.168.90.3"
    puppetServer.vm.provision "shell", inline: $install_puppet
    puppetServer.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "puppet/modules"
    end
  end

end