Vagrant.configure("2") do |config|
  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-20.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
  end

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.network "forwarded_port", guest: 3000, host: 8030
    servidorUbuntu.vm.network "forwarded_port", guest: 80, host: 8080
    servidorUbuntu.vm.synced_folder "./sync", "/home/vagrant/sync"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end
end

#lxc list
#lxc image list
#lxc laucn images:ubuntu/20.04 server

## Enter as sudo to container  
# sudo lxc exec server bash


##Push file from sync folder to server/root 
# lxc file push sync/server.js server/root/Projects/node/server.js

## Portforwarding-
# lxc config device list server
'''
Port forwarding local VM (192.168.100.3) 2200 - container 22 ssh
Port forwarding local VM (192.168.100.3) 3000 - container 80 node server
'''

##ssh a contenedores
# ssh-keygen #en VM
# ssh-copy-id 2200 remoto@10.242.79.179

# ssh remoto@10.242.79.179
# scp file.txt remoto@10.242.79.179:/~


## con portforwarding si estoy en otra máquina
# ssh -p 2200 remoto@192.168.100.3
# scp -P 2200 file.txt remoto@192.168.100.3:~/

##copiar archivos con ssh
#scp -P 2200 file.txt remoto@192.168.100.3:~/


##Live migration
'''
When a checkpoint saved on one host is
restored on a different host, that is called live migration.

Stateless: 
Cuando no interesa el estado de lo que este en el contenedor.

Stateful:
Cuando el backup depende de información pasada (estado) para funcionar correctamente,
generalmente pasa con servicios u aplicaciones.



'''
#CRIU = Checkpoint Restore in Userspace

# sudo add-apt-repository ppa:criu/ppa
# sudo apt-get install criu