Vagrant.configure("2") do |config|
  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "bento/ubuntu-20.04"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
  end
  
  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-20.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end

  config.vm.define :server1 do |server1|
    server1.vm.box = "bento/ubuntu-20.04"
    server1.vm.network :private_network, ip: "192.168.100.4"
    server1.vm.provision "shell", path: "bootstrap.sh"
    server1.vm.hostname = "server1"
  end

  config.vm.define :server2 do |server2|
    server2.vm.box = "bento/ubuntu-20.04"
    server2.vm.network :private_network, ip: "192.168.100.5"
    server2.vm.provision "shell", path: "bootstrap.sh"
    server2.vm.hostname = "server2"
  end

end

#lxc exec web1 /bin/bash

#lxc config device info